version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    image: aws-flashcards:v2
    environment:
      - TZ=America/Santiago
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.flashcards.rule=Host(`flashcards.home.arpa`)"
        - "traefik.http.routers.flashcards.entrypoints=web"
        - "traefik.http.routers.flashcards.service=flashcards-svc"
        - "traefik.http.services.flashcards-svc.loadbalancer.server.port=80"

  backend:
    image: ghcr.io/muchobien/pocketbase:latest
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.flashcards-api.rule=Host(`api.flashcards.home.arpa`)"
        - "traefik.http.routers.flashcards-api.entrypoints=web"
        - "traefik.http.services.flashcards-api.loadbalancer.server.port=8090"

volumes:
  pb_data:

networks:
  proxy:
    external: true
